-- Up Migration

ALTER TABLE recipes
ADD COLUMN subtitle VARCHAR(150) NOT NULL,
ADD COLUMN calories INT,
ADD COLUMN protein DECIMAL(5,2),
ADD COLUMN carbs DECIMAL(5,2),
ADD COLUMN fat DECIMAL(5,2),
ADD COLUMN sugars DECIMAL(5,2),
ADD COLUMN fiber DECIMAL(5,2),
ADD COLUMN saturated_fat DECIMAL(5,2),
ADD COLUMN sodium INT,
ADD COLUMN meal_types TEXT[] DEFAULT '{}',
ADD COLUMN dietary_preferences TEXT[] DEFAULT '{}',
DROP COLUMN IF EXISTS prep_time;

ALTER TABLE ingredients
ADD COLUMN unit TEXT,
ADD COLUMN optional BOOLEAN,
ALTER COLUMN quantity TYPE DECIMAL USING quantity::DECIMAL;

-- Down Migration

ALTER TABLE recipes
DROP COLUMN IF EXISTS subtitle,
DROP COLUMN IF EXISTS calories,
DROP COLUMN IF EXISTS protein,
DROP COLUMN IF EXISTS carbs,
DROP COLUMN IF EXISTS fat,
DROP COLUMN IF EXISTS sugars,
DROP COLUMN IF EXISTS fiber,
DROP COLUMN IF EXISTS saturated_fat,
DROP COLUMN IF EXISTS sodium,
DROP COLUMN IF EXISTS meal_types,
DROP COLUMN IF EXISTS dietary_preferences,
ADD COLUMN prep_time INT;

ALTER TABLE ingredients
DROP COLUMN unit,
DROP COLUMN optional,
ALTER COLUMN quantity TYPE TEXT USING quantity::TEXT;