export const tasks = [
  {
    id: "RECIPE-0001",
    title: "Classic Spaghetti Bolognese",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Traditional italian pasta with a savory, slow-simmered meat and tomato sauce.",
    cuisine: "italian",
    cookTime: 30,
    difficulty: "medium",
    mealType: "dinner",
    imageUrl: "",
  },
  {
    id: "RECIPE-0002",
    title: "Fluffy Buttermilk Pancakes",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Light, airy pancakes that are perfect for a comforting breakfast or brunch.",
    cuisine: "american",
    cookTime: 15,
    difficulty: "easy",
    mealType: "breakfast",
    imageUrl: "",
  },
  {
    id: "RECIPE-0003",
    title: "Authentic indian Chicken Curry",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Tender chicken simmered in a richly spiced onion and tomato curry base.",
    cuisine: "indian",
    cookTime: 40,
    difficulty: "hard",
    mealType: "dinner",
    imageUrl: "",
  },
  {
    id: "RECIPE-0004",
    title: "Vegetarian Maki Sushi Rolls",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Simple and fresh sushi rolls filled with seasoned rice, avocado, and cucumber.",
    cuisine: "japanese",
    cookTime: 15,
    difficulty: "hard",
    mealType: "lunch",
    imageUrl: "",
  },
  {
    id: "RECIPE-0005",
    title: "Seasoned Beef Tacos",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Crispy taco shells filled with spiced ground beef, lettuce, and shredded cheese.",
    cuisine: "mexican",
    cookTime: 20,
    difficulty: "easy",
    mealType: "lunch",
    imageUrl: "",
  },
  {
    id: "RECIPE-0006",
    title: "Crisp Caesar Salad",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Classic Caesar salad with crunchy croutons and creamy dressing.",
    cuisine: "american",
    cookTime: 0,
    difficulty: "easy",
    mealType: "lunch",
    imageUrl: "",
  },
  {
    id: "RECIPE-0007",
    title: "Crispy Grilled Cheese Sandwich",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Buttery, golden sandwich filled with melted cheddar cheese.",
    cuisine: "american",
    cookTime: 10,
    difficulty: "easy",
    mealType: "lunch",
    imageUrl: "",
  },
  {
    id: "RECIPE-0008",
    title: "Thai Shrimp Pad Thai",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "A vibrant stir-fried noodle dish with shrimp, egg, and bean sprouts in a tangy sauce.",
    cuisine: "thai",
    cookTime: 15,
    difficulty: "medium",
    mealType: "dinner",
    imageUrl: "",
  },
  {
    id: "RECIPE-0010",
    title: "Quick Vegetable Stir-Fry",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "A fast, flavorful mix of stir-fried vegetables with garlic and soy sauce.",
    cuisine: "chinese",
    cookTime: 10,
    difficulty: "easy",
    mealType: "lunch",
    imageUrl: "",
  },
  {
    id: "RECIPE-0011",
    title: "Fresh Greek Salad",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "A refreshing salad of crisp vegetables, briny olives, and creamy feta.",
    cuisine: "greek",
    cookTime: 0,
    difficulty: "easy",
    mealType: "lunch",
    imageUrl: "",
  },
  {
    id: "RECIPE-0012",
    title: "Creamy indian Butter Chicken",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Marinated chicken cooked in a rich tomato-based sauce with butter and cream.",
    cuisine: "indian",
    cookTime: 30,
    difficulty: "hard",
    mealType: "dinner",
    imageUrl: "",
  },
  {
    id: "RECIPE-0013",
    title: "Herby Crusted Chicken",
    subtitle: "with Garlic Bread and Roasted Vegetables",
    description: "Juicy chicken breasts coated in herbs with garlic bread and roasted vegetables, finished with sweet chilli mayo.",
    cuisine: "Classic",
    cookTime: 25,
    difficulty: "easy",
    mealType: "dinner",
    imageUrl: "",
  },
  {
    id: "RECIPE-0014",
    title: "Mushroom Risotto",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Creamy arborio rice slowly cooked with broth and loaded with savory mushrooms.",
    cuisine: "italian",
    cookTime: 30,
    difficulty: "hard",
    mealType: "dinner",
    imageUrl: "",
  },
  {
    id: "RECIPE-0015",
    title: "Avocado Toast with Poached Egg",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Crunchy toast topped with creamy avocado and a perfectly poached egg.",
    cuisine: "american",
    cookTime: 5,
    difficulty: "easy",
    mealType: "breakfast",
    imageUrl: "",
  },
  {
    id: "RECIPE-0016",
    title: "Sweet Potato Fries",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Crispy baked sweet potato fries with a hint of spice.",
    cuisine: "american",
    cookTime: 25,
    difficulty: "easy",
    mealType: "snack",
    imageUrl: "",
  },
  {
    id: "RECIPE-0017",
    title: "Egg Fried Rice",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Quick and tasty stir-fried rice with scrambled egg and vegetables.",
    cuisine: "chinese",
    cookTime: 15,
    difficulty: "easy",
    mealType: "lunch",
    imageUrl: "",
  },
  {
    id: "RECIPE-0018",
    title: "French Onion Soup",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Rich beef broth with caramelized onions topped with melted cheese and bread.",
    cuisine: "french",
    cookTime: 45,
    difficulty: "hard",
    mealType: "dinner",
    imageUrl: "",
  },
  {
    id: "RECIPE-0019",
    title: "Beef Stroganoff",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Tender beef strips in a creamy mushroom sauce served over noodles.",
    cuisine: "Russian",
    cookTime: 30,
    difficulty: "medium",
    mealType: "dinner",
    imageUrl: "",
  },
  {
    id: "RECIPE-0020",
    title: "Caprese Salad",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Fresh tomatoes, mozzarella, and basil with a drizzle of balsamic glaze.",
    cuisine: "italian",
    cookTime: 0,
    difficulty: "easy",
    mealType: "lunch",
    imageUrl: "",
  },
  {
    id: "RECIPE-0021",
    title: "Creamy Spinach Artichoke Dip",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Warm, cheesy dip packed with spinach and artichokes, perfect for sharing.",
    cuisine: "american",
    cookTime: 20,
    difficulty: "easy",
    mealType: "snack",
    imageUrl: "",
  },
  {
    id: "RECIPE-0022",
    title: "Banana Oatmeal Cookies",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Soft, chewy cookies made with ripe bananas and oats—naturally sweet and healthy.",
    cuisine: "american",
    cookTime: 15,
    difficulty: "easy",
    mealType: "snack",
    imageUrl: "",
  },
  {
    id: "RECIPE-0023",
    title: "Tuna Salad Sandwich",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Quick sandwich with a creamy tuna filling, perfect for lunch.",
    cuisine: "american",
    cookTime: 0,
    difficulty: "easy",
    mealType: "lunch",
    imageUrl: "",
  },
  {
    id: "RECIPE-0024",
    title: "Chocolate Mug Cake",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Single-serve chocolate cake made in the microwave in just minutes.",
    cuisine: "american",
    cookTime: 2,
    difficulty: "easy",
    mealType: "snack",
    imageUrl: "",
  },
  {
    id: "RECIPE-0025",
    title: "Avocado Toast",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "Simple and delicious toast topped with creamy mashed avocado, a touch of lemon, and optional seasonings.",
    cuisine: "american",
    cookTime: 2,
    difficulty: "easy",
    mealType: "breakfast",
    imageUrl: "",
  },
  {
    id: "RECIPE-0026",
    title: "Yogurt Parfait",
    subtitle: "lorem ipsum nova isto tavoiem presto legiuno",
    description: "A light, refreshing layered treat with creamy yogurt, fresh fruit, and crunchy granola.",
    cuisine: "american",
    cookTime: 0,
    difficulty: "easy",
    mealType: "breakfast",
    imageUrl: "",
  }
];
