services:
  postgres:
    image: postgres:15
    container_name: cookbook_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cookbook_network

  backend:
    image: imseanconroy/cookbook-backend:0.0.1
    container_name: cookbook_backend
    restart: always
    environment:
      NODE_ENV: production
      PORT: 5000
      READ_ONLY: ${READ_ONLY}
      LOG_LEVEL: ${LOG_LEVEL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
    ports:
      - "${BACKEND_PORT}:5000"
    depends_on:
      - postgres
    networks:
      - cookbook_network

  frontend:
    image: imseanconroy/cookbook-frontend:0.0.1
    container_name: cookbook_frontend
    restart: always
    environment:
      VITE_BASE_URL: ${BACKEND_URL}
      VITE_READ_ONLY: ${READ_ONLY}
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - cookbook_network

networks:
  cookbook_network:

volumes:
  postgres_data: